name: capstone_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.3
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.1.0

  cloud_functions: ^6.0.4
  firebase_storage: ^13.0.0
  google_sign_in: ^7.2.0

  file_picker: ^11.0.2
  provider: ^6.1.5
 

  pdf: ^3.11.3
  
  syncfusion_flutter_pdf: ^33.2.6
  flutter_dotenv: ^6.0.0
  foundation: ^0.0.5
  intl: ^0.20.2
  uuid: ^4.5.1
  http: ^1.4.0

  fl_chart: ^1.2.0



  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  flutter_linkify: ^6.0.0
  docx_to_text: ^1.0.1
  universal_html: ^2.3.0


  speech_to_text: ^7.2.0

  typed_data: ^1.4.0
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  google_mlkit_text_recognition: ^0.15.0



  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1

  flutter_local_notifications: ^21.0.0
  markdown: ^7.3.0
  flutter_markdown_plus: ^1.0.5
  timeago: ^3.7.1
  open_file: ^3.5.11
  csv: ^8.0.0
  path_provider: ^2.1.5





dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/images/google.png
    - lib/images/phone_number.png
    - lib/images/guest.png
    - lib/images/oasp.png
    - .env
