// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU84t3Q2F0fpltpaNxcZn6IIH12GFoZ5o',
    appId: '1:1008880584715:web:4cdd73d822348cb67f5f0e',
    messagingSenderId: '1008880584715',
    projectId: 'capstone-project-1703b',
    authDomain: 'capstone-project-1703b.firebaseapp.com',
    storageBucket: 'capstone-project-1703b.firebasestorage.app',
    measurementId: 'G-2EKTRB7T8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlQvaLh8nosnyr7O3yTM1aCSE1xf93bQY',
    appId: '1:1008880584715:android:586d0981fcdb06057f5f0e',
    messagingSenderId: '1008880584715',
    projectId: 'capstone-project-1703b',
    storageBucket: 'capstone-project-1703b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl1nyCF4OnKwWTNnt64Gsz9bO0Mdpzzws',
    appId: '1:1008880584715:ios:987e171471089c577f5f0e',
    messagingSenderId: '1008880584715',
    projectId: 'capstone-project-1703b',
    storageBucket: 'capstone-project-1703b.firebasestorage.app',
    androidClientId: '1008880584715-5t9ueo6uip9ge1dgf3he4vn6calb6jne.apps.googleusercontent.com',
    iosClientId: '1008880584715-agrc825q27btck9nv23hg7s59sfc0dcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl1nyCF4OnKwWTNnt64Gsz9bO0Mdpzzws',
    appId: '1:1008880584715:ios:987e171471089c577f5f0e',
    messagingSenderId: '1008880584715',
    projectId: 'capstone-project-1703b',
    storageBucket: 'capstone-project-1703b.firebasestorage.app',
    androidClientId: '1008880584715-5t9ueo6uip9ge1dgf3he4vn6calb6jne.apps.googleusercontent.com',
    iosClientId: '1008880584715-agrc825q27btck9nv23hg7s59sfc0dcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU84t3Q2F0fpltpaNxcZn6IIH12GFoZ5o',
    appId: '1:1008880584715:web:f6006b38f583ff137f5f0e',
    messagingSenderId: '1008880584715',
    projectId: 'capstone-project-1703b',
    authDomain: 'capstone-project-1703b.firebaseapp.com',
    storageBucket: 'capstone-project-1703b.firebasestorage.app',
    measurementId: 'G-E9J1G333NQ',
  );

}