// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUD3KueYe9JK77bXMLpy5Cx1ZzLdN_zow',
    appId: '1:13855273820:web:419125e9643d3c0cd94799',
    messagingSenderId: '13855273820',
    projectId: 'cmu-oasp-assist',
    authDomain: 'cmu-oasp-assist.firebaseapp.com',
    storageBucket: 'cmu-oasp-assist.firebasestorage.app',
    measurementId: 'G-C4ZGZVLQRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkSXKcHhlhLUdf97nKJ1zEA0nyPS5VNeM',
    appId: '1:13855273820:android:ea1cd67d149ffc5cd94799',
    messagingSenderId: '13855273820',
    projectId: 'cmu-oasp-assist',
    storageBucket: 'cmu-oasp-assist.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMwF9lOUgUbjCVxEhHOow0l4G7TDegr60',
    appId: '1:13855273820:ios:3c398048bab6c282d94799',
    messagingSenderId: '13855273820',
    projectId: 'cmu-oasp-assist',
    storageBucket: 'cmu-oasp-assist.firebasestorage.app',
    iosBundleId: 'com.example.capstoneProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMwF9lOUgUbjCVxEhHOow0l4G7TDegr60',
    appId: '1:13855273820:ios:3c398048bab6c282d94799',
    messagingSenderId: '13855273820',
    projectId: 'cmu-oasp-assist',
    storageBucket: 'cmu-oasp-assist.firebasestorage.app',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUD3KueYe9JK77bXMLpy5Cx1ZzLdN_zow',
    appId: '1:13855273820:web:26ee87175cc6dfdbd94799',
    messagingSenderId: '13855273820',
    projectId: 'cmu-oasp-assist',
    authDomain: 'cmu-oasp-assist.firebaseapp.com',
    storageBucket: 'cmu-oasp-assist.firebasestorage.app',
    measurementId: 'G-696MW34QVX',
  );
}
